name:                taxo-gen
version:             0.1.0.0
github:              "githubuser/taxo-gen"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/taxo-gen#readme>

dependencies:
- base >= 4.7 && < 5
- deepseq
- lens
- math-functions
- MemoTrie
- mtl
- multiset
- parallel
- random-fu

library:
  source-dirs: src

executables:
  taxo-gen-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-M2G
    - -with-rtsopts=-N2
    dependencies:
    - taxo-gen

tests:
  taxo-gen-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - taxo-gen
